"""Resuming from a checkpoint must not duplicate trajectory frames.

Frames stream to HDF5 every ``save_freq`` cycles; checkpoints are written only
every ``checkpoint_freq`` cycles. A crash between two checkpoints -- the normal
case, since that is what checkpointing is for -- therefore leaves frames on disk
for cycles *after* the last checkpoint.

The driver loaded the whole stored trajectory and then re-ran from
``checkpoint_cycle + 1``, so those cycles were both loaded and regenerated. The
resumed trajectory came out longer than an uninterrupted run, and the extra frames
belong to a discarded branch: they are not merely redundant, they are wrong.

Nothing recorded how many frames existed when the checkpoint was taken, so the
fix is to record that and truncate on load.
"""

from __future__ import annotations

import numpy as np
import pytest

h5py = pytest.importorskip("h5py")

from pathgennie.core.storage import HDF5Storage  # noqa: E402


def _frame(i):
    return np.full((2, 3), float(i))


def _write(path, n_before, cycle, n_after):
    """Stream frames, checkpoint, then stream more -- i.e. crash after a checkpoint."""
    storage = HDF5Storage(path)
    for i in range(n_before):
        storage.append("trajectory", _frame(i))
        storage.append("metric", np.array([float(i)]))
    storage.save_checkpoint(
        cycle=cycle, rng_state=np.random.default_rng(0).bit_generator.state,
        anchor_coords=_frame(n_before), anchor_cv=np.zeros(1), anchor_metric=0.0,
    )
    for i in range(n_before, n_before + n_after):
        storage.append("trajectory", _frame(i))
        storage.append("metric", np.array([float(i)]))
    storage.close()
    return path


def test_checkpoint_records_the_frame_count(tmp_path):
    """Without this the truncation is impossible -- nothing else identifies the cut."""
    path = _write(tmp_path / "a.h5", n_before=5, cycle=5, n_after=3)
    with h5py.File(path, "r") as f:
        assert "n_frames" in f["checkpoint"].attrs
        assert int(f["checkpoint"].attrs["n_frames"]) == 5


def test_load_returns_only_frames_up_to_the_checkpoint(tmp_path):
    """The core defect: 8 frames on disk, but only 5 belong to the checkpoint."""
    path = _write(tmp_path / "b.h5", n_before=5, cycle=5, n_after=3)
    ckpt = HDF5Storage.load_checkpoint(path)
    assert len(ckpt["trajectory"]) == 5, (
        f"got {len(ckpt['trajectory'])} frames; the 3 written after the checkpoint "
        "will be regenerated by the resumed run and duplicated")
    # And they must be the *right* five, in order.
    assert np.allclose([fr[0, 0] for fr in ckpt["trajectory"]], np.arange(5))


def test_metric_history_is_truncated_consistently(tmp_path):
    path = _write(tmp_path / "c.h5", n_before=4, cycle=4, n_after=6)
    ckpt = HDF5Storage.load_checkpoint(path)
    assert len(ckpt["trajectory"]) == 4
    assert len(ckpt["metric_history"]) == 4, \
        "metrics and frames must stay aligned or the CV of frame k is wrong"


def test_the_stale_rows_are_removed_from_disk(tmp_path):
    """Truncation must reach the file too.

    Otherwise the resumed run appends after the stale rows and the next load sees
    them again -- the duplication returns on the second resume.
    """
    path = _write(tmp_path / "d.h5", n_before=5, cycle=5, n_after=3)
    HDF5Storage.load_checkpoint(path)
    with h5py.File(path, "r") as f:
        assert f["trajectory"].shape[0] == 5
        assert f["metric"].shape[0] == 5


def test_no_truncation_when_the_checkpoint_is_the_last_thing_written(tmp_path):
    path = _write(tmp_path / "e.h5", n_before=6, cycle=6, n_after=0)
    ckpt = HDF5Storage.load_checkpoint(path)
    assert len(ckpt["trajectory"]) == 6


def test_legacy_checkpoints_without_n_frames_still_load(tmp_path):
    """Old files predate the attribute; they must not crash, just skip truncation."""
    path = _write(tmp_path / "f.h5", n_before=3, cycle=3, n_after=2)
    with h5py.File(path, "a") as f:
        del f["checkpoint"].attrs["n_frames"]
    ckpt = HDF5Storage.load_checkpoint(path)
    assert ckpt is not None
    assert len(ckpt["trajectory"]) == 5      # untruncated, the old behaviour


def test_resumed_trajectory_matches_an_uninterrupted_run(tmp_path):
    """End to end: the resumed frame sequence must equal the uninterrupted one."""
    uninterrupted = [_frame(i) for i in range(5)]

    path = _write(tmp_path / "g.h5", n_before=5, cycle=5, n_after=4)
    ckpt = HDF5Storage.load_checkpoint(path)
    resumed = list(ckpt["trajectory"])

    assert len(resumed) == len(uninterrupted)
    for a, b in zip(resumed, uninterrupted):
        assert np.allclose(a, b)
